#!/usr/bin/env python3
"""Generate an interactive HTML step-by-step implementation tutorial and open it in the browser."""

import json
import re
import sys
import webbrowser
from pathlib import Path
from datetime import datetime


def generate_html(data: dict) -> str:
    title = data.get("title", "Implementation Tutorial")
    summary = data.get("summary", "")
    files_touched = data.get("files", [])
    steps = data.get("steps", [])
    verification = data.get("verification", {})

    # Build file tags
    file_tags = "".join(
        f'<span class="file-tag">{_esc(f)}</span>' for f in files_touched
    )
    file_list_html = (
        f'<div class="file-list">{file_tags}</div>' if files_touched else ""
    )

    # Build steps
    steps_html = []
    for i, step in enumerate(steps, 1):
        step_title = step.get("title", f"Step {i}")
        file_path = step.get("file", "")
        location = step.get("location", "")
        description = step.get("description", "")
        code = step.get("code", "")
        lang = step.get("lang", "")
        notes = step.get("notes", [])
        diff_lines = step.get("diff", [])

        # File badge
        file_badge = (
            f'<span class="file-badge">{_esc(file_path)}</span>' if file_path else ""
        )

        # Location line
        location_html = (
            f'<div class="location">{_esc(location)}</div>' if location else ""
        )

        # Code block — either diff-style or plain
        code_html = ""
        if diff_lines:
            lines = []
            for dl in diff_lines:
                line_type = dl.get("type", "context")  # add, remove, context
                line_text = dl.get("text", "")
                css_class = f"line-{line_type}"
                prefix = {"add": "+ ", "remove": "- ", "context": "  "}.get(
                    line_type, "  "
                )
                lines.append(
                    f'<span class="{css_class}">{_esc(prefix + line_text)}</span>'
                )
            lang_label = (
                f'<span class="lang-label">{_esc(lang)}</span>' if lang else ""
            )
            code_html = f'<pre>{lang_label}<code>{"".join(lines)}</code></pre>'
        elif code:
            lang_label = (
                f'<span class="lang-label">{_esc(lang)}</span>' if lang else ""
            )
            code_html = f"<pre>{lang_label}<code>{_esc(code)}</code></pre>"

        # Notes / callouts
        notes_html = ""
        for note in notes:
            ntype = note.get("type", "tip")
            icon = {"tip": "\U0001f4a1", "warning": "\u26a0\ufe0f", "danger": "\U0001f6a8"}.get(
                ntype, "\U0001f4a1"
            )
            notes_html += (
                f'<div class="callout {_esc(ntype)}">'
                f'<span class="callout-icon">{icon}</span>'
                f'<span>{_esc(note.get("text", ""))}</span></div>'
            )

        # Connector between steps (except after last)
        connector = (
            '<div class="connector"><div class="line"></div></div>'
            if i < len(steps)
            else ""
        )

        steps_html.append(f"""<div class="step">
    <div class="step-number">{i}</div>
    <div class="step-header">
      <h2>{_esc(step_title)}</h2>
      {file_badge}
    </div>
    {location_html}
    <p>{_esc(description)}</p>
    {code_html}
    {notes_html}
  </div>
  {connector}""")

    # Build verification section
    verify_html = ""
    if verification:
        verify_desc = verification.get("description", "How to test:")
        verify_steps = verification.get("steps", [])
        verify_command = verification.get("command", "")

        items = "".join(f"<li>{_esc_rich(s)}</li>" for s in verify_steps)
        cmd_html = (
            f'<pre><code>{_esc(verify_command)}</code></pre>' if verify_command else ""
        )

        verify_html = f"""<div class="verification">
    <h2>\u2705 Verification</h2>
    <p>{_esc(verify_desc)}</p>
    <ol>{items}</ol>
    {cmd_html}
  </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Show Me: {_esc(title)}</title>
  <style>{CSS}</style>
</head>
<body>
  <div class="header">
    <div class="badge">Implementation Tutorial</div>
    <h1>{_esc(title)}</h1>
    <p>{_esc(summary)}</p>
    {file_list_html}
  </div>
  {"".join(steps_html)}
  {verify_html}
  <div class="footer">Generated by /showme &mdash; claude-ode &mdash; {datetime.now().strftime("%Y-%m-%d %H:%M")}</div>
</body>
</html>"""


def _esc(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _esc_rich(text: str) -> str:
    """Escape HTML but preserve inline code backticks as <code> tags."""
    escaped = _esc(text)
    return re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)


CSS = """
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  --bg: #0f1117;
  --surface: #1a1d27;
  --border: #2a2e3a;
  --text: #e4e4e7;
  --text-muted: #9ca3af;
  --accent: #818cf8;
  --accent-dim: rgba(129, 140, 248, 0.12);
  --success: #34d399;
  --success-dim: rgba(52, 211, 153, 0.12);
  --warning: #fbbf24;
  --warning-dim: rgba(251, 191, 36, 0.12);
  --danger: #f87171;
  --danger-dim: rgba(248, 113, 113, 0.12);
  --code-bg: #141620;
  --radius: 12px;
  --font-mono: 'SF Mono', 'Fira Code', 'JetBrains Mono', monospace;
  --font-sans: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

body {
  font-family: var(--font-sans);
  background: var(--bg);
  color: var(--text);
  line-height: 1.7;
  padding: 2rem;
  max-width: 900px;
  margin: 0 auto;
}

.header {
  position: relative;
  padding: 2.5rem 2rem 2rem;
  margin-bottom: 2rem;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  overflow: hidden;
}
.header::before {
  content: '';
  position: absolute;
  top: 0; left: 0; right: 0;
  height: 4px;
  background: linear-gradient(90deg, var(--success), #34d3e0, var(--accent));
}
.header .badge {
  display: inline-block;
  font-size: 0.7rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--success);
  background: var(--success-dim);
  padding: 0.25rem 0.75rem;
  border-radius: 999px;
  margin-bottom: 1rem;
}
.header h1 { font-size: 1.75rem; font-weight: 700; line-height: 1.3; margin-bottom: 0.5rem; }
.header p { color: var(--text-muted); font-size: 0.95rem; }
.header .file-list { display: flex; flex-wrap: wrap; gap: 0.4rem; margin-top: 1rem; }
.header .file-tag {
  font-family: var(--font-mono);
  font-size: 0.75rem;
  background: var(--code-bg);
  border: 1px solid var(--border);
  padding: 0.2rem 0.6rem;
  border-radius: 6px;
  color: var(--text-muted);
}

.step {
  position: relative;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 1.75rem 2rem;
  margin-bottom: 1.25rem;
  transition: border-color 0.2s;
}
.step:hover { border-color: var(--accent); }

.step-number {
  position: absolute;
  top: -0.75rem;
  left: 1.5rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px; height: 28px;
  background: var(--accent);
  color: var(--bg);
  font-size: 0.8rem;
  font-weight: 700;
  border-radius: 50%;
}

.step-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 0.75rem;
  gap: 1rem;
}
.step h2 { font-size: 1.1rem; font-weight: 600; }
.step .file-badge {
  flex-shrink: 0;
  font-family: var(--font-mono);
  font-size: 0.75rem;
  background: var(--accent-dim);
  color: var(--accent);
  padding: 0.25rem 0.75rem;
  border-radius: 6px;
}
.step .location {
  font-size: 0.82rem;
  color: var(--text-muted);
  margin-bottom: 0.75rem;
  font-family: var(--font-mono);
}
.step p, .step li { color: var(--text-muted); font-size: 0.9rem; line-height: 1.75; }
.step ul, .step ol { padding-left: 1.25rem; margin-top: 0.5rem; }
.step li { margin-bottom: 0.4rem; }
.step li strong { color: var(--text); }

pre {
  background: var(--code-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem 1.25rem;
  overflow-x: auto;
  margin: 0.75rem 0;
  font-family: var(--font-mono);
  font-size: 0.82rem;
  line-height: 1.7;
  color: var(--text-muted);
  position: relative;
}
pre .lang-label {
  position: absolute;
  top: 0.5rem;
  right: 0.75rem;
  font-size: 0.65rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: var(--text-muted);
  opacity: 0.5;
}
code {
  font-family: var(--font-mono);
  font-size: 0.85em;
  background: var(--code-bg);
  padding: 0.15em 0.4em;
  border-radius: 4px;
  color: var(--accent);
}
pre code { background: none; padding: 0; color: inherit; }

.line-add {
  background: rgba(52, 211, 153, 0.1);
  display: block;
  margin: 0 -1.25rem;
  padding: 0 1.25rem;
  border-left: 3px solid var(--success);
}
.line-remove {
  background: rgba(248, 113, 113, 0.1);
  display: block;
  margin: 0 -1.25rem;
  padding: 0 1.25rem;
  border-left: 3px solid var(--danger);
  text-decoration: line-through;
  opacity: 0.6;
}
.line-context {
  display: block;
  margin: 0 -1.25rem;
  padding: 0 1.25rem;
  opacity: 0.5;
}

.callout {
  display: flex;
  gap: 0.75rem;
  padding: 1rem 1.25rem;
  border-radius: 8px;
  margin: 0.75rem 0;
  font-size: 0.85rem;
  line-height: 1.6;
}
.callout.tip { background: var(--success-dim); border-left: 3px solid var(--success); }
.callout.warning { background: var(--warning-dim); border-left: 3px solid var(--warning); }
.callout.danger { background: var(--danger-dim); border-left: 3px solid var(--danger); }
.callout-icon { flex-shrink: 0; font-size: 1.1rem; }

.connector { display: flex; justify-content: center; padding: 0.25rem 0; }
.connector .line { width: 2px; height: 20px; background: var(--border); border-radius: 1px; }

.verification {
  background: var(--surface);
  border: 2px solid var(--success);
  border-radius: var(--radius);
  padding: 1.75rem 2rem;
  margin-top: 1.25rem;
}
.verification h2 {
  color: var(--success);
  font-size: 1.1rem;
  font-weight: 600;
  margin-bottom: 0.75rem;
}
.verification p, .verification li { color: var(--text-muted); font-size: 0.9rem; line-height: 1.75; }
.verification ul, .verification ol { padding-left: 1.25rem; margin-top: 0.5rem; }
.verification li { margin-bottom: 0.4rem; }

a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

.footer {
  text-align: center;
  color: var(--text-muted);
  font-size: 0.75rem;
  margin-top: 2rem;
  padding-top: 1.5rem;
  border-top: 1px solid var(--border);
}
"""


if __name__ == "__main__":
    if len(sys.argv) >= 2:
        # JSON passed as argument (simple payloads)
        raw = sys.argv[1]
    elif not sys.stdin.isatty():
        # JSON piped via stdin (handles multiline content cleanly)
        raw = sys.stdin.read()
    else:
        print(
            "Usage: python generate.py '<json-data>'\n"
            "   or: echo '<json-data>' | python generate.py",
            file=sys.stderr,
        )
        print(
            "\nExpected JSON with: title, summary, files, steps, verification",
            file=sys.stderr,
        )
        sys.exit(1)

    data = json.loads(raw)
    html = generate_html(data)

    out = Path(f"/tmp/showme-{int(datetime.now().timestamp())}.html")
    out.write_text(html)
    print(f"Tutorial generated: {out}")
    webbrowser.open(f"file://{out}")
